/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rs.ac.bg.fon.ai.server.view;

import java.io.IOException;

import rs.ac.bg.fon.ai.server.threads.ServerThread;

/**
 *
 * @author nkala
 */
public class ServerForm extends javax.swing.JFrame {

    private ServerThread serverThread;

    /**
     * Creates new form ServerForm
     */
    public ServerForm() {
        initComponents();
        miStopServer.setEnabled(false);
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBarServer = new javax.swing.JMenuBar();
        menuServer = new javax.swing.JMenu();
        miStartServer = new javax.swing.JMenuItem();
        miStopServer = new javax.swing.JMenuItem();
        miClients = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuServer.setText("Server");

        miStartServer.setText("Start server");
        miStartServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miStartServerActionPerformed(evt);
            }
        });
        menuServer.add(miStartServer);

        miStopServer.setText("Stop Server");
        miStopServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miStopServerActionPerformed(evt);
            }
        });
        menuServer.add(miStopServer);

        miClients.setText("Clients");
        miClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miClientsActionPerformed(evt);
            }
        });
        menuServer.add(miClients);

        menuBarServer.add(menuServer);

        jMenu2.setText("Configuration");

        jMenuItem1.setText("Database config");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        menuBarServer.add(jMenu2);

        setJMenuBar(menuBarServer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miClientsActionPerformed
        ClientsDialog clientsDialog = new ClientsDialog(this, true);
        clientsDialog.setVisible(true);

    }//GEN-LAST:event_miClientsActionPerformed

    private void miStartServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miStartServerActionPerformed
        if (serverThread == null || !serverThread.isAlive()) {
            try {
                serverThread = new ServerThread();
                serverThread.start();
                miStartServer.setEnabled(false);
                miStopServer.setEnabled(true);
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_miStartServerActionPerformed

    private void miStopServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miStopServerActionPerformed
        if (serverThread != null && serverThread.getServerSocket().isBound()) {
            try {
                serverThread.getServerSocket().close();
                miStartServer.setEnabled(true);
                miStopServer.setEnabled(false);
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_miStopServerActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        DatabaseConfigDialog dialog = new DatabaseConfigDialog(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar menuBarServer;
    private javax.swing.JMenu menuServer;
    private javax.swing.JMenuItem miClients;
    private javax.swing.JMenuItem miStartServer;
    private javax.swing.JMenuItem miStopServer;
    // End of variables declaration//GEN-END:variables
}
