/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package rs.ac.bg.fon.ai.client.forms;

import java.sql.SQLException;

import javax.swing.JOptionPane;

import rs.ac.bg.fon.ai.client.components.TableModelHall;
import rs.ac.bg.fon.ai.client.logic.Controller;
import rs.ac.bg.fon.ai.communication.model.Hall;

/**
 *
 * @author nkala
 */
public class HallDialog extends javax.swing.JDialog {

    private TableModelHall model;
    private Hall hallToEdit;
    private boolean isEditMode = false;

    // Konstruktor za dodavanje
    public HallDialog(java.awt.Frame parent, boolean modal, TableModelHall model) {
        super(parent, modal);
        this.model = model;
        initComponents();
        setLocationRelativeTo(parent);
        setTitle("Dodaj salu");
        pack();
        setLocationRelativeTo(parent);
    }

    // Konstruktor za izmenu
    public HallDialog(javax.swing.JFrame parent, boolean modal, TableModelHall model, Hall hallToEdit) {
        super(parent, modal);
        this.model = model;
        this.hallToEdit = hallToEdit;
        this.isEditMode = true;
        initComponents();
        setLocationRelativeTo(parent);
        setTitle("Izmeni salu");
        populateFields();
        pack();
        setLocationRelativeTo(parent);
    }

    private void populateFields() {
        if (hallToEdit != null) {
            txtNaziv.setText(hallToEdit.getName());
            txtKapacitet.setText(String.valueOf(hallToEdit.getCapacity()));
            jButton1.setText("Izmeni");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNaziv = new javax.swing.JTextField();
        txtKapacitet = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Naziv sale:");

        jLabel2.setText("Kapacitet:");

        jButton1.setText("Dodaj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtKapacitet, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtKapacitet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // Validacija sa akumuliranjem grešaka
            String errorMessage = validateHallInput();
            if (!errorMessage.isEmpty()) {
                throw new Exception(errorMessage);
            }

            String name = txtNaziv.getText().trim();
            String broj = txtKapacitet.getText().trim();
            int kapacitet = Integer.parseInt(broj);

            try {
                if (isEditMode && hallToEdit != null) {
                    // Edit mode - proveri da li postoje buduće projekcije
                    boolean hasUpcomingProjections = Controller.getInstance().hasUpcomingProjectionsForHall(hallToEdit);
                    if (hasUpcomingProjections) {
                        throw new Exception("Ne možete izmeniti salu jer postoje projekcije koje predstoje u ovoj sali!");
                    }

                    Hall updatedHall = new Hall(name, kapacitet);
                    updatedHall.setId(hallToEdit.getId()); // ← OVO JE KLJUČNO! Zadrži isti ID

                    // PRVO pokušaj update u bazi
                    Controller.getInstance().updateHall(updatedHall);

                    // TEK ONDA ako je uspešno, ažuriraj lokalni objekat i model
                    hallToEdit.setName(name);
                    hallToEdit.setCapacity(kapacitet);
                    model.updateHall(hallToEdit);
                    JOptionPane.showMessageDialog(this, "Sala uspešno izmenjena!");

                } else {
                    // Add mode
                    Hall h = new Hall(name, kapacitet);
                    h = Controller.getInstance().saveHall(h);
                    model.addHall(h);
                    JOptionPane.showMessageDialog(this, "Sala uspešno dodata!");
                }

                dispose();
            } catch (SQLException ex) {
                throw new Exception("Greška u bazi podataka: " + ex.getMessage());
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška:\n" + ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private String validateHallInput() {
        StringBuilder errorMessage = new StringBuilder();

        // Validacija naziva
        String name = txtNaziv.getText().trim();
        if (name.isEmpty()) {
            errorMessage.append("• Naziv sale je obavezan!\n");
        } else if (name.length() < 2) {
            errorMessage.append("• Naziv sale mora imati najmanje 2 karaktera!\n");
        }

        // Validacija kapaciteta
        String broj = txtKapacitet.getText().trim();
        if (broj.isEmpty()) {
            errorMessage.append("• Kapacitet je obavezan!\n");
        } else {
            try {
                int kapacitet = Integer.parseInt(broj);
                if (kapacitet <= 0) {
                    errorMessage.append("• Kapacitet mora biti pozitivan broj!\n");
                } else if (kapacitet > 1000) {
                    errorMessage.append("• Kapacitet ne može biti veći od 1000!\n");
                }
            } catch (NumberFormatException e) {
                errorMessage.append("• Kapacitet mora biti broj!\n");
            }
        }

        return errorMessage.toString();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtKapacitet;
    private javax.swing.JTextField txtNaziv;
    // End of variables declaration//GEN-END:variables
}
